import {
  Affix,
  Alert,
  AutoComplete,
  Avatar,
  BackTop,
  Badge,
  Breadcrumb,
  BreadcrumbItem,
  Button,
  ButtonGroup,
  Card,
  Carousel,
  CarouselItem,
  Cascader,
  Checkbox,
  CheckboxGroup,
  Circle,
  Col,
  Collapse,
  ColorPicker,
  Content,
  DatePicker,
  Dropdown,
  DropdownItem,
  DropdownMenu,
  Footer,
  Form,
  FormItem,
  Header,
  Icon,
  Input,
  InputNumber,
  Layout,
  Menu,
  MenuGroup,
  MenuItem,
  Sider,
  Submenu,
  Modal,
  Option,
  OptionGroup,
  Page,
  Panel,
  Poptip,
  Progress,
  Radio,
  RadioGroup,
  Rate,
  Row,
  Select,
  Slider,
  Spin,
  Step,
  Steps,
  Switch,
  Table,
  Tabs,
  TabPane,
  Tag,
  Timeline,
  TimelineItem,
  TimePicker,
  Tooltip,
  Transfer,
  Tree,
  Upload,
}  from   'iview'
// 这里是重点
const iview = {
  install: function(Vue){
    Vue.component('iAffix',Affix)
    Vue.component('iAlert',Alert)
    Vue.component('iAutoComplete',AutoComplete)
    Vue.component('iAvatar',Avatar)
    Vue.component('iBackTop',BackTop)
    Vue.component('iBadge',Badge)
    Vue.component('iBreadcrumb',Breadcrumb)
    Vue.component('iBreadcrumbItem',BreadcrumbItem)
    Vue.component('iButton',Button)
    Vue.component('iButtonGroup',ButtonGroup)
    Vue.component('iCard',Card)
    Vue.component('iCarousel',Carousel)
    Vue.component('iCarouselItem',CarouselItem)
    Vue.component('iCascader',Cascader)
    Vue.component('iCheckbox',Checkbox)
    Vue.component('iCheckboxGroup',CheckboxGroup)
    Vue.component('iCircle',Circle)
    Vue.component('iCol',Col)
    Vue.component('iCollapse',Collapse)
    Vue.component('iColorPicker',ColorPicker)
    Vue.component('iContent',Content)
    Vue.component('iDatePicker',DatePicker)
    Vue.component('iDropdown',Dropdown)
    Vue.component('iDropdownItem',DropdownItem)
    Vue.component('iDropdownMenu',DropdownMenu)
    Vue.component('iFooter',Footer)
    Vue.component('iForm',Form)
    Vue.component('iFormItem',FormItem)
    Vue.component('iHeader',Header)
    Vue.component('iIcon',Icon)
    Vue.component('iInput',Input)
    Vue.component('iInputNumber',InputNumber)
    Vue.component('iLayout',Layout)
    Vue.component('iMenu',Menu)
    Vue.component('iMenuGroup',MenuGroup)
    Vue.component('iMenuItem',MenuItem)
    Vue.component('iSider',Sider)
    Vue.component('iSubmenu',Submenu)
    Vue.component('iModal',Modal)
    Vue.component('iOption',Option)
    Vue.component('iOptionGroup',OptionGroup)
    Vue.component('iPage',Page)
    Vue.component('iPanel',Panel)
    Vue.component('iPoptip',Poptip)
    Vue.component('iProgress',Progress)
    Vue.component('iRadio',Radio)
    Vue.component('iRadioGroup',RadioGroup)
    Vue.component('iRate',Rate)
    Vue.component('iRow',Row)
    Vue.component('iSelect',Select)
    Vue.component('iSlider',Slider)
    Vue.component('iSpin',Spin)
    Vue.component('iStep',Step)
    Vue.component('iSteps',Steps)
    Vue.component('iSwitch',Switch)
    Vue.component('iTable',Table)
    Vue.component('iTabs',Tabs)
    Vue.component('iTabPane',TabPane)
    Vue.component('iTag',Tag)
    Vue.component('iTimeline',Timeline)
    Vue.component('iTimelineItem',TimelineItem)
    Vue.component('iTimePicker',TimePicker)
    Vue.component('iTooltip',Tooltip)
    Vue.component('iTransfer',Transfer)
    Vue.component('iTree',Tree)
    Vue.component('iUpload',Upload)
  }
}

// 导出组件
export default iview
